"use client";

import type { Scores } from "./scoring";
import { ARCHETYPE_BLURB, DIMENSIONS } from "./scoring";

export interface ReportData {
  id: number;
  archetype: string;
  scores: Scores;
}

// Build and download the executive PDF report on the client.
// @react-pdf/renderer is imported dynamically so it never enters the server bundle.
export async function downloadReport(data: ReportData): Promise<void> {
  const { Document, Page, Text, View, StyleSheet, pdf } = await import("@react-pdf/renderer");
  const React = (await import("react")).default;

  const styles = StyleSheet.create({
    page: { padding: 40, fontSize: 12, color: "#111827", fontFamily: "Helvetica" },
    brand: { fontSize: 10, color: "#6366f1", letterSpacing: 2, marginBottom: 6 },
    title: { fontSize: 24, fontWeight: 700, marginBottom: 4 },
    sub: { fontSize: 11, color: "#6b7280", marginBottom: 20 },
    archetype: { fontSize: 18, color: "#4f46e5", marginBottom: 6 },
    blurb: { fontSize: 11, lineHeight: 1.5, marginBottom: 24, color: "#374151" },
    sectionTitle: { fontSize: 13, fontWeight: 700, marginBottom: 10 },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      borderBottom: "1px solid #e5e7eb",
      paddingVertical: 8,
    },
    dim: { fontSize: 12 },
    score: { fontSize: 12, fontWeight: 700 },
    footer: { position: "absolute", bottom: 32, left: 40, right: 40, fontSize: 9, color: "#9ca3af" },
  });

  const doc = React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(Text, { style: styles.brand }, "SAGA MATRIX · EXECUTIVE REPORT"),
      React.createElement(Text, { style: styles.title }, "Leadership Diagnostic Summary"),
      React.createElement(Text, { style: styles.sub }, `Submission #${data.id}`),
      React.createElement(Text, { style: styles.archetype }, `Archetype: ${data.archetype}`),
      React.createElement(Text, { style: styles.blurb }, ARCHETYPE_BLURB[data.archetype] ?? ""),
      React.createElement(Text, { style: styles.sectionTitle }, "Dimension scores (0–100)"),
      ...DIMENSIONS.map((dim) =>
        React.createElement(
          View,
          { key: dim, style: styles.row },
          React.createElement(Text, { style: styles.dim }, dim),
          React.createElement(Text, { style: styles.score }, String(data.scores[dim]))
        )
      ),
      React.createElement(
        Text,
        { style: styles.footer },
        "Generated by the Saga Matrix Diagnostic Tool — assessment → scoring → archetype → reporting."
      )
    )
  );

  const blob = await pdf(doc).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `saga-matrix-report-${data.id}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
